name: 'Report Billing Summary'
description: "Report membership and licenses statistics for your GitHub Organization."
inputs:
  organization-name:
    description: 'Name of the GitHub Organization'
    required: true
  organization-id:
    description: 'ID of the GitHub Organization'
    required: true
  token:
    description: 'Access Token'
    required: true
  google-chat-webhook-url:
    description: 'Google Chat webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'