name: 'Notify Cleanup Users'
description: 'Notify Google Chat about inactive users in a GitHub Organization'
inputs:
  inactive-users:
    description: 'List of inactive users'
    required: true
  ignored-users:
    description: 'List of ignored users'
    required: false
  google-chat-webhook-url:
    description: 'Google Chat webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'